on: push

jobs:
  test:
    runs-on: scale-set-k8s-dind
    container:
      image: ubuntu:latest
    steps:
      - run: env
      - run: apt-get update
      - run: apt-get install -y curl jq
      - run: curl https://reqres.in/api/users/ | jq
      - run: sleep 30
      - run: echo "BYEEE!!!!"
