on:
  push:
  pull_request:

jobs:
  deploy-env:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - run: echo "Hello World"
  other-deploy-same-env:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - run: echo "Hello World"
  deploy-envless:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
