on: push

jobs:
  test:
    runs-on: arc-runner-set
    container:
      image: alpine:latest
    steps:
      - run: env
      - run: cat /etc/release || true
      - run: echo "hello" > world.txt
      # - uses: actions/upload-artifact@v4
      #   with:
      #     path: world.txt
      #     name: world.txt

