on: push

jobs:
  test:
    runs-on: scale-set-k8s
    container:
      image: alpine:latest
    steps:
      - run: env
      - run: echo "hello" > world.txt
      - run: sleep 5000
      # - uses: actions/upload-artifact@v4
      #   with:
      #     path: world.txt
      #     name: world.txt

