on: push

jobs:
  test:
    runs-on: scale-set-k8s
    container:
      image: registry.1password.io/dev/build-release/docker/node-slim:1.0.0
    steps:
      - run: env
      - run: cat /etc/release || true
      - run: echo "hello" > world.txt
      # - uses: actions/upload-artifact@v4
      #   with:
      #     path: world.txt
      #     name: world.txt

