on:
  push:
  pull_request:

env:
  IS_NULL: ${{ null }}
  IS_EMPTY: ""

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: echo "hello" > world.txt
      - uses: actions/upload-artifact@v4
        with:
          path: world.txt
          name: world.txt
  release:
    needs: [test]
    uses: ./.github/workflows/sub1.yaml
