on: push

jobs:
  test:
    runs-on: arc-runner-set
    steps:
      - run: env
      - run: echo "hello" > world.txt
      - uses: actions/upload-artifact@v4
        with:
          path: world.txt
          name: world.txt

