on: push

jobs:
  test:
    runs-on: scale-set-k8s
    container:
      image: public.ecr.aws/docker/library/alpine:latest
    steps:
      - run: env
      - run: cat /etc/release || true
      - run: echo "hello" > world.txt
      # - uses: actions/upload-artifact@v4
      #   with:
      #     path: world.txt
      #     name: world.txt

