on: push

jobs:
  deploy-env:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - run: echo "Hello World"
  deploy-envless:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
