on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - uses: actions/download-artifact@v4
        with:
          name: foo
      - run: echo "got here!"
      - run: ls
