# This is a basic workflow to help you get started with Actions

name: call test

# Controls when the workflow will run
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    uses: ./.github/workflows/callable/test.yaml
